FROM huggingface/transformers-pytorch-gpu

COPY vit_jax/requirements.txt requirements.txt

USER root

RUN apt-get update && apt-get install -y git

RUN pip install -r requirements.txt

RUN pip install transformers

RUN pip install opencv-python-headless

COPY HappyFace.jpg .
COPY HappySquare.jpg Happy.jpg
COPY Disgust.jpg .
COPY Angry.jpg .
COPY main.py main.py

CMD ["python3", "main.py"]